### ISSUE TITLE
undefined method 'opaque' for URI

### ISSUE THREAD

**Issue by mhusmann** [crystal-lang/crystal-db#102]
When compiling a source with crystal 0.28.0 getting the following error message:
in lib/sqlite3/src/sqlite3/connection.cr:15: undefined method 'opaque' for URI (did you mean 'opaque?'?) 
connection.cr
15: uri.opaque.not_nil!

**Comment by Blacksmoke16** [comment]
This issue is with the sqlite3 shard, and has already been fixed. 

See https://github.com/crystal-lang/crystal-sqlite3/blob/master/CHANGELOG.md#v0110-2019-04-18

**Comment by mhusmann** [comment]
It runs now.
Thanks a lot.
