### ISSUE TITLE
retry instead of raise on initial connection

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/crystal-db#103]
I'm working on dockerizing a lucky app, and I noticed that if my postgres service is still booting up when the lucky one is started, I get the following:

`Unhandled exception:  (DB::ConnectionRefused)`

The database url I'm using is: `postgres://postgres:@postgres:5432/postgres?retry_attempts=10` but after a little digging it seems the initial connection logic is *not* covered by a `retry` so it just fails outright.

Is that expected / intended behavior (don't retry on initial connection) or am I misunderstanding?

One way to engineer around the problem is to just make sure postgres is ready for connections before letting docker start the lucky service, but the Docker docs bring up a good point:

> The problem of waiting for a database (for example) to be ready is really just a subset of a much larger problem of distributed systems. In production, your database could become unavailable or move hosts at any time. Your application needs to be resilient to these types of failures.
>
> To handle this, design your application to attempt to re-establish a connection to the database after a failure. If the application retries the connection, it can eventually connect to the database.
[source](https://docs.docker.com/compose/startup-order/)

`crystal-db` in accordance with this advice, does retry on `ConnectionLost` and `ConnectionRefused` ([source](https://github.com/crystal-lang/crystal-db/blob/master/src/db/pool.cr#L84-L106)) but that's the pool. Before the pool can start working, it has to make a connection and the pg driver fails us out. That happens [around here](https://github.com/crystal-lang/crystal-db/blob/master/src/db/database.cr#L51-L53) in this repo and [right here](https://github.com/will/crystal-pg/blob/master/src/pg/connection.cr#L16) in pg.

So what do folks here think, is it desirable or possible for `crystal-db` to retry on a failed initial connection?

**Comment by bcardiff** [comment]
I choose not to retry on a failed initial connection in to quickly raise an error if there is a connection misconfiguration like wrong host, database name, or credentials.

Otherwise, the timeout of the retry will slow down that scenario.

`DB.connect` can be used to check if a connection can be established in the app if needed as a  workaround today.

**Comment by KCErb** [comment]
Right, that makes sense. I don't suppose there would be any way to distinguish between something wrong on my end and something wrong on the db end so it's something we'd only run into on the first connection. And I agree, it's better in that case to fail quickly.

This feels then like a one-off, special-to-docker-compose initialization issue. And there are dockery ways around this kind of thing (just in case someone comes googling along, I'm talking about this: https://stackoverflow.com/questions/48684609/control-startup-order-in-docker-compose).

So for me this answers the issue I wanted to bring up. I'll go ahead and close but please (anyone) reopen if you have a different viewpoint, i.e. that there should be a way to retry on the initial connection.
