### ISSUE TITLE
ResultSet should provide #column_names as well as #column_name(x)

### ISSUE THREAD

**Issue by anicholson** [crystal-lang/crystal-db#11]
It seems odd to me that in order to get the column names of a `ResultSet`, I need to do:

```(0..column_count).map { |i| column_name(i) }```

Couldn't this be promoted to `ResultSet`'s public API?

**Comment by asterite** [comment]
Good idea! :-)

**Comment by anicholson** [comment]
Holy crap, that's the fastest turnaround time I've ever seen! 0_o thanks @asterite! :)
