### ISSUE TITLE
A better error for "no results"

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal-db#120]
Right now if your query doesn't return anything, an exception is raised saying [no results](https://github.com/crystal-lang/crystal-db/blob/master/src/db/statement.cr#L18).

I'd like to propose this become a special class like `raise NoResultsException.new("no results")`. This would allow libraries that wrap this to catch on that error specifically to handle things specialized for that library.

**Comment by straight-shoota** [comment]
It should probably be named `NoResultsError`, but yes that seems like a good idea :+1:
