### ISSUE TITLE
Extract ConnectionPool to its own shard?

### ISSUE THREAD

**Issue by jgaskins** [crystal-lang/crystal-db#122]
I've been using the [`pool` shard](https://github.com/ysbaddaden/pool) for a generic connection pool but I had some issues with it when using `-Dpreview_mt` and, since the `ConnectionPool` implementation in this shard is both powerful and threadsafe, I wonder if it would be useful to extract it to its own shard to become the de facto standard connection pool implementation.

I've used it in the [`neo4j` shard](https://github.com/jgaskins/neo4j.cr/blob/add-cluster-support/src/neo4j/connection_pool.cr) and applied only minimal tweaks to get it working there — rather than add checkout callbacks to the connection, I removed their calls in the pool.

Any thoughts on this?

**Comment by straight-shoota** [comment]
Sounds like a good idea to generalize the pool implementation for other use cases.

`ysbaddaden/pool` is used as a dependency by a few other shards as well, so there's a demand for a general purpose pool implementation ([dependents](https://shardbox.org/shards/pool/releases/0.2.3/dependencies)).

However, I'm not too fond of a micro shard that would only provide a single, relatively smallish feature. Maybe it's fine. But what about leaving the implementation in `crystal-db`, but still generalizing it to work for other use cases?
The difference would only be whether you install and require a dedicated pool shard or `crystal-db` and only use `DB::Pool`.

**Comment by jgaskins** [comment]
The `stefanwille/redis` shard using it is actually the primary reason I was looking at generalizing this implementation. As long as I'm using that shard, I can't use `-Dpreview_mt` since I store my HTTP sessions in Redis. I just pushed [my fork that uses `DB::Pool`](https://github.com/stefanwille/crystal-redis/compare/stefanwille:master...jgaskins:use-crystal-db-pool), which was a decent way to show how this connection pool needs to change (or, at least, how I needed it to change) to support arbitrary connections:

- More stats available
- `src/db/pool.cr` doesn't load the exception classes, but does reference them
  - The file that contains the exception classes references classes provided by the shard other than exceptions
    - It doesn't load them and I don't believe it should
    - Maybe a single file with all exceptions might not be the right abstraction?

I ended up loading the complete shard to use `DB::Pool`. Ideally, I'd just be able to `require "db/pool"` and it wouldn't load parts the pool doesn't need.

**Comment by RX14** [comment]
> However, I'm not too fond of a micro shard that would only provide a single, relatively smallish feature

This is an argument for not extracting it into a shard prematurely, however it's clear from the number of shards with the `pool` dependency that this would benefit from being extracted. Connection pools are actually rather complex, as the number of issues in this repo and others testifies to.

**Comment by straight-shoota** [comment]
Maybe we could also consider adding a connection pool implementation to stdlib... sounds too specific at first, but we'll need this for `HTTP::Client` eventually. I'm not sure though, if that wouldn't require a very specialized pool that couldn't be generalized for other use cases.

**Comment by bcardiff** [comment]
The downside of extracting is loosing some cohesive context for the configuration.
I'm fine with refactoring the db/pool so it can be required on its own as a first step.

Note there are further lifecycle policy that are not yet implemented. Maximum lifetime of the source is pretty generic. But maybe if we extract we might loose some further improvements specific to the use case.

**Comment by jgaskins** [comment]
> The downside of extracting is loosing some cohesive context for the configuration.

I don't think I understand. How is configuration different based on whether the implementation is provided by the gem?

> maybe if we extract we might loose some further improvements specific to the use case.

I sympathize with this, but I don't know that it would limit what could be done here. This shard could extend the extracted generalized implementation, for example.

```ruby
module DB
  class Pool(T) < TheGeneralizedPool(T)
    def initialize(@specialized_option = 1, **args)
      super(**args) 
    end

    def specialized_feature
      # ...
    end
  end
end
```

With that said, I'm on board with refactoring to allow it to be required on its own as a stepping stone to extracting it. I can work on a PR this weekend unless one of you has already started playing around with the idea.

**Comment by bcardiff** [comment]
While doing that, maybe it might be worth creating a samples directory to stress the `require "db/pool"` (probably `require "../src/db/pool"`) use case.

Regarding the configuration, the issue for me is that with extracting it to shard there is a bit of tension between saying: go and check the pool shard for configuration vs. hey here are all the pool configuration options for the db. One is more indirect for the reader and the other generate some duplication.

**Comment by j8r** [comment]
@jgaskins Are you still working on the issue, how is it going?

**Comment by jgaskins** [comment]
Sorry for the delay here. Been a hell of a few months. Just posted #131 for this.
