### ISSUE TITLE
View entire prepared query string without executing a query

### ISSUE THREAD

**Issue by samueleaton** [crystal-lang/crystal-db#130]
Is there a way to generate the entire query string with prepared statements without running the query against the database?

It appears that any method that takes an `args` array hits the database in the same method.

I need access to the raw query that will be executed so I can `EXPLAIN QUERY PLAN #{my_query}` during development to see if the database is using indexes on that query.

Example

```crystal
stmt = connection.build(
  "SELECT first_name, last_name FROM employees WHERE id = ? AND is_active = ?",
  args: [17, 1]
)
stmt.prepared_query
  #=> "SELECT first_name, last_name FROM employees WHERE id = 17 AND is_active = 1"
```

This would allow me to print raw queries to the console during development and check that they are all optimized.

**Comment by straight-shoota** [comment]
I don't think this can work because this expanded query doesn't even exist on the client. It's only put together by the database server, based on the prepared statement and the arguments.
You could try to recreate that behaviour, but there would be no guarantee that it's equivalent to what happens on the server. So probably not useful for analyzing query plans.

You might consider a server-side query log, though. That should help you for this use case.

**Comment by samueleaton** [comment]
@straight-shoota hmmm... I'm using sqlite and from the looks of it, it doesn't support logging.

I didn't realize that prepared statements we part of the DB API, i thought that was a client thing. i learned something.

I'm not sure if Crystal us using the C bindings for SQLite, but it looks like it has the option to generate expanded SQL output using `sqlite3_expanded_sql()` in the C bindings
https://www.sqlite.org/c3ref/expanded_sql.html

**Comment by straight-shoota** [comment]
I don't know how the sqlite driver works.
Seems like a discussion for https://github.com/crystal-lang/crystal-sqlite3

**Comment by rdp** [comment]
Postgres does this internally, well I believe with newer'ish Postgres if you query pg_stat_activity it'll show you the actual query including parameters.  You may be able to monkey patch the query method and have it spit out the "theoretical" expanded query: https://groups.google.com/g/crystal-lang/c/BJet6TPteHM/m/V-3fR78EBgAJ
