### ISSUE TITLE
Provide a unified way of escaping strings for database.

### ISSUE THREAD

**Issue by kyku** [crystal-lang/crystal-db#132]
As queries must often be created dynamically it is pretty handy to have some parts of them escaped by the database library, in order to prevent syntax errors and, in the worst case, SQL injections. It appears that Crystal DB does not provide such methods yet.

**Comment by Blacksmoke16** [comment]
To be clear, this issue is mainly about turning arrays into lists for use in `IN` clauses.  Currently, as far as I can tell thru testing, having a query like:

```cr
db.query "SELECT ... FROM ... WHERE x IN ?", my_array
```

Isn't currently possible.

**Comment by kyku** [comment]
@Blacksmoke16 , this is an interesting question, as there seems to be several variants of escaping depending on context. For example the PHP binding to PostgreSQL includes: pg_escape_identifier, pg_escape_literal, pg_escape_string and pg_escape_bytea.

**Comment by Blacksmoke16** [comment]
@kyku I'm pretty sure primitive values are are already handled, like if you did `SELECT ... WHERE id = ?, 1`, or `SELECT ... WHERE title = ?, "foobar"`, I'm pretty sure both of these would work.  IMO the main issue when using an array is it isn't a primitive value, so probably just isn't handled.

At the very least, I'd imagine something should be exposed to help with this specific use case of using an array with an `IN` clause.

**Comment by straight-shoota** [comment]
crystal-db supports query parameters very well. See https://crystal-lang.org/reference/database/#exec for usage examples. Their implementations however are entirely handled by the DB driver, not crystal-db. There is no generic solution to this. It must be driver specific.

Most (if not all) drivers even delegate this to the database server directly in form of prepared statments and query arguments.

@kyku I don't understand your specific problem. Is it what @Blacksmoke16 assumed?

That's actually asking the wrong question then. The SQL `IN` operator operates on a list of expressions, not an array (which would be a single expression). So an `IN` operand must be raw SQL, it can't be a parameter. There's really nothing to do about this here.
Some higher-level DB frameworks or ORMs may help with building safe SQL expressions, but that's not a feature for crystal-db because it's driver-specific.

**Comment by straight-shoota** [comment]
Ah I just found the original forum post at https://forum.crystal-lang.org/t/escape-in-crystal-db/2270 Would be nice to add a cross reference to such previous discussions.

So my last paragraph applies to your problem.

**Comment by kyku** [comment]
@straight-shoota , no, we have slightly digressed from the original query post. I was wandering if it is possible to actually escape a string rather than have it bound as a prepared statement parameter.

That is to say, to have something like this:
`db.query "SELECT #{db.escape_identifier column_name} FROM #{db.escape_identifier table_name} WHERE name=#{db.escape_string some_string}"
`

While the "#{db.escape_string some_string}" part can be replaced with '?', I bet "#{db.escape_identifier column_name}" can not.

**Comment by RX14** [comment]
go's sqlx simply provides a function to support IN queries, since that's the only place where it's difficult. I'd suggest the same approach here.

**Comment by straight-shoota** [comment]
@kyku Yes, that's definitely possible. But as I mentioned above, such behaviour is specific to the database. There can't be a generic solution. Drivers should provide such methods if and when appropriate. `crystal-pg` for example defines `PG::Connection#escape_literal` and `PG::Connection#escape_identifier` methods for this use case.
Other drivers should probably do the same.

**Comment by kyku** [comment]
@straight-shoota, thanks for pointing this out. I'm am mainly concentrating on MYSQL driver which does not seem to provide such functionality. But then, if some drivers already provide those methods, is there any problem with adding them to the rest and bubbling this up as DB instance method?

**Comment by straight-shoota** [comment]
> is there any problem with adding them to the rest and bubbling this up as DB instance method?

Generalizations only make sense when they're useful for database-agnostic use cases. But escapes depend on the syntax of the query language. If you use them, you have database-specific code. Syntax is different between drivers. Not just the implementations differ, but different databases can also have different types of escapes. Hence the drivers may expose different methods (or method signatures).

**Comment by bcardiff** [comment]
Custom drives can have additional methods beyond crystal-db API.
crystal-db avoid changing or building sql statements.

If there is a way to have the list of elements as arguments like using JSON datatype then maybe that would be path to go that will avoid escaping or building manually the statements. Note that crystal-mysql does not support JSON datatype yet.
