### ISSUE TITLE
Streaming mapping

### ISSUE THREAD

**Issue by crisward** [crystal-lang/crystal-db#14]
Is there any way to stream a response one row at a time to json.
I have a Class setup for my database rows with `DB.mapping` and `JSON.mapping`. However `MYTABLE.from_rs(rs).to_json` seems to process the whole result set. 

I'd like to do this one at a time, so I can push to the output buffer and use less memory, especially for large result sets.

If this is not possible, can you point to where in the code I should look to add this feature.

Thanks.

**Comment by asterite** [comment]
Hi!

I spent a few minutes trying to see why it was consuming the whole result set and I finally understood how it works, it just lacks some docs.

You can do `MYTABLE.new(rs).to_json`.

That is, `from_rs` consumes a whole result set and returns an array of results, while `new` creates just one entity. So, in a way, this is similar to the `new(pull : JSON::PullParser)` that `JSON.mapping` defines :-)

**Comment by crisward** [comment]
Ah thanks for that. I've worked out quite a bit of the library by looking at the comments / code. I may have a go at expanding the readme and do a pull request if I get chance. May a little quick start guide for using mapping, connection pools etc.

**Comment by bcardiff** [comment]
Note that for streaming data, instead of doing a whole large json you might prefer NDJSON. 
Generating NDJSON is kind of easy in crystal since it's a puts of the json of one object. 
In order to generate the whole json, without allocating the whole dataset, you will need to manually/Json::Builder to generate the extra symbols.

**Comment by crisward** [comment]
I've done this in kemal, it fetches around 1.3million rows from mariadb in 8 seconds.

```crystal
    def all(ctx) 
      ctx.response.content_type = "application/json; charset=utf-8"
      ctx.response.print %{\{"status":"success","data":[}
      @db.query("SELECT id,first_name,surname,email FROM users where deleted_at is null") do |rs|
        firstrow = true
        rs.each do
          ctx.response.print "," if !firstrow
          ctx.response.print User.new(rs).to_json
          firstrow = false
        end
      end
      "]}"
    end
```
Users.from_rs(rs)  used > 700mb ram. Now it uses around 200mb. However the number doesn't go down after the request has ended. Should the GC kick in and return ram to the system?

**Comment by crisward** [comment]
That's weird. Just create a compiled version, it's now using only 3mb?

**Comment by RX14** [comment]
@crisward the GC doesn't have to reclaim memory as soon as it's unused. It'll be reclaimed sometime in the future.

I also rewrote your example using JSON::Builder:
```cr
def all(ctx) 
  ctx.response.content_type = "application/json; charset=utf-8"
  ctx.response.json_object do |object|
    object.field("status", "success")
    object.field("data") do
      ctx.response.json_array do |array|
        @db.query("SELECT id,first_name,surname,email FROM users where deleted_at is null") do |rs|
        rs.each do
          array.push { User.new(rs).to_json(ctx.response) }
        end
      end
    end
  end
end
```

I think `JSON::Builder` needs some work...

**Comment by bcardiff** [comment]
If User is a struct instead of a class there should be much less memory allocation. The same as using `ResultSet#read` directly.

**Comment by crisward** [comment]
I'll swap to struct and see what happens. Json Build looks like it's building a large string in memory, is this right or is it streaming it out?

**Comment by bcardiff** [comment]
@crisward hard to tell without source. But something like this avoids creating a string with the whole json representation (and returns ndjson)

```crystal
require "http/server"
require "json"

server = HTTP::Server.new "0.0.0.0", 5678 do |context|
  10.times do |i|
    context.response.json_object do |object|
      object.field "id", i
      object.field "name", "name of #{i}"
    end
    context.response.puts
  end
end

puts "Listening on http://0.0.0.0:5678"
server.listen
```

**Comment by luislavena** [comment]
@crisward [JSON::Builder](https://github.com/crystal-lang/crystal/blob/master/src/json/to_json.cr#L75) is what `to_json` from `JSON.mapping` uses:

https://github.com/crystal-lang/crystal/blob/master/src/json/mapping.cr#L144

Invoking `to_json` with an IO instance (like `context.response`) will stream the response instead of building a String in memory.

The argless `to_json` method uses `String.build` to provide an IO and build an string (see JSON::Builder link above)

I've used the IO approach on my end to reduce the allocated objects, however, I'm not sure the response is streamed right away but definitely is not allocating all the response in memory like Ruby.

Cheers.

**Comment by luislavena** [comment]
> I'm not sure the response is streamed right away

Actually by doing `context.response.flush` the response becomes *chunked* :smile:

**Comment by crisward** [comment]
@luislavena Thanks for the explanation... @bcardiff thanks, I'm outputing to a xhr request in a browser. Not sure ndjson is as quick to parse in the browser. The large number of rows is just me messing around seeing how well crystal performs. But streaming the content is definitely more performant. I'll give json builder a go as it looks a little nicer than my string concat.

**Comment by crisward** [comment]
I've pretty much got the answer I was after so I'll close this. Thanks everyone for your help.
