### ISSUE TITLE
Transactions don't return the result of the yielded block

### ISSUE THREAD

**Issue by matthewmcgarvey** [crystal-lang/crystal-db#145]
It currently returns a boolean of whether or not the transaction was committed successfully https://github.com/crystal-lang/crystal-db/blob/eaddae7d71d52536453ea2d94777854f1b057f83/src/db/begin_transaction.cr#L29

This is different than Rails, for instance, that does return that value https://github.com/rails/rails/blob/d5386cfba2ec5c80f09e37d44b87bcae9c6ab6a8/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L310-L312

I would rather get the result of the block rather than the vague boolean, though I know this will be a breaking change.

**Comment by bcardiff** [comment]
I agree. I didn't consider the return value for this method.

**Comment by BrucePerens** [comment]
This has sat around for a while now. I think I would like to add #transaction! which:
* Returns the value of the block unconditionally.
* Raises a unique exception when the transaction is rolled back.

**Comment by bcardiff** [comment]
The return value can be added to the existing method. There is no documentation for the return value. The current (nilable) boolean is accidental.
