### ISSUE TITLE
id cast from Nil to Int64 failed

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal-db#15]
```
$ cat test2.cr
require "db"
require "sqlite3"

class Url
  DB.mapping({
    id: Int64,
    name:  {type: String},
    age: {type: Int32},
  })
end

DB.open "sqlite3:./file.db" do |db|
  db.exec "create table if not exists contacts (id primary key, name string, age integer)"
  db.exec "insert into contacts (name, age) values (\"name\", 33);"
  rs = db.query("SELECT id, name, age from contacts")
  Url.from_rs(rs)
end
$ crystal test2.cr
cast from Nil to Int64 failed, at ...libs/db/db/result_set.cr:80 (TypeCastError)
```

Not sure if it's a DB or sqlite3 issue

**Comment by asterite** [comment]
Missing autoincrement the id? Primary key alone doesn't do that

**Comment by rdp** [comment]
smaller example:

```
require "db"
require "sqlite3"

DB.open "sqlite3:./file.db" do |db|
  db.exec "create table if not exists contacts (age integer)"
  db.exec "insert into contacts (age) values (33);"
  rs = db.query("SELECT age from contacts")
  rs.read(Int32)
end
```

If I added this (obviously wrong) diff to sqlite3:

```
--- a/src/sqlite3/result_set.cr
+++ b/src/sqlite3/result_set.cr
@@ -23,6 +23,7 @@ class SQLite3::ResultSet < DB::ResultSet
   end

   def read
+   move_next
     col = @column_index
     value =
       case LibSQLite3.column_type(self, col)

```

then my smaller example here starts working, FWIW...

**Comment by asterite** [comment]
This works:

```cr
class Url
  DB.mapping({
    id:   Int64,
    name: {type: String},
    age:  {type: Int32},
  })
end

DB.open "sqlite3:./file.db" do |db|
  db.exec "drop table if exists contacts"
  db.exec "create table if not exists contacts (id integer primary key autoincrement, name string, age integer)"
  db.exec "insert into contacts (name, age) values (\"name\", 33);"
  rs = db.query("SELECT id, name, age from contacts")
  Url.from_rs(rs)
end
```

Note the "id integer primary key autoincrement".

If `id` is nilable, like in your case (because you are inserting something without an id), then map it to `Int64?` or use `{type: Int64, nilable: true}`.

Isn't that the problem?

**Comment by bcardiff** [comment]
The return value of query is expected to be used inside a each block or a while that use move_next. If you want only one results use scalar or query_one. (Over mobile here, sorry for not showing snippets). 

Maybe the result_set could have a nicer error if read is called and move_next hasn't been called.

**Comment by rdp** [comment]
OK thank you for your help, it appears my failure was in declaring the primary key as "id primary key" which apparently meant "typeless" (I thought it would default to auto-incremented int, wow was I wrong).  Since it is "typeless" you can insert int or string or null into this, so my insert was setting a "null" to the id.  I thought I had double checked this by verifying that the sql for last_insert_rowid() was non zero (it is) but then this value wasn't assigned to the id, my bad.

So, for followers, this meant I had inserted "null" into what I thought was an "int only" column.  Coincidentally, if I add nilable: true as mentioned, to the id spec(    id: {type: Int64, nilable: true}, ), then it works (id is assigned to Nil so I conveniently the mapping works there to crystal, I guess an Int64 | Nil type or some odd).

As a side note, it also apparently has to be "integer primary key auto increment" (not "int") for that to be automatically propagated.  Thanks again.
