### ISSUE TITLE
How to map a joint?

### ISSUE THREAD

**Issue by Nicolab** [crystal-lang/crystal-db#150]
Hello,

Please, how to map a joint?

Example:

```crystal
db.query_all(
  "select users.* as user, posts.* as posts from users left join posts on posts.user_id = users.id", 
  as: {user: User, posts: Post?}
)
```

or maybe something like this:

```crystal
db.query_all(
  "select users.*, posts.* from users left join posts on posts.user_id = users.id", 
  as: {User, Post?}
)
```

But doesn't work.
> Note: User and Post include DB::Serializable

The idea is to get the result like:

* one instance `user.posts # => Array(Post)` 
* or two `user # => User` and posts # => Array(Post)`
* even a Tuple (or NamedTuple) to do a post processing

if you know an example or a solution, it would be very useful.

**Comment by straight-shoota** [comment]
Answered at https://forum.crystal-lang.org/t/how-to-map-a-joint-with-crystal-db/3102/2

Please avoid cross-posting questions here, that is better served at the forum. Thanks.
