### ISSUE TITLE
single connections should be able to have multiple outstanding resultsets

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal-db#16]
possibly same as #13 (?), each statement has its own cursor (at least I think so?) so each db conn should be allowed more than one outstanding query, today the following yields a db connection timeout.  At the least, this code should not results in a timeout failure by default:

```
require "db"
require "sqlite3"

DB.open "sqlite3:./file2.db" do |db|
  db.exec "create table if not exists contacts (age integer)"
  db.exec "insert into contacts (age) values (33);"
  db.query("SELECT age from contacts") do |rs|
    rs2 = db.query ("select 1;")
  end
end
```

**Comment by bcardiff** [comment]
When the database is accessed via a socket you can only have one statement/query running at the same time.

Maybe drivers implementation should tell if they are concurrent-safe so the underlying connection is not locked. On other drivers the above code will work thanks to the connection pool.

**Comment by bcardiff** [comment]
Even with #13 I think the connection should have a life cycle check and know if it's busy or idle. That way better error messages can be done if the state is not the appropriate. So the above code will suffer of the same problems with `DB.connect`. Unless drivers implementation are marked somehow as concurrent-safe.

**Comment by rdp** [comment]
OK I think I see, the problem is that within a block you could read from "both" result sets so it doesn't work on one connection.  For some reason I thought it was possible. Thanks for clearing that one up.

**Comment by bcardiff** [comment]
It should be possible in sqlite, but not thanks to the connection pool over a socket but due to the nature of the library. I haven't figure out how the connection pool should deal with sqlite yet, but definitely should work.

**Comment by bcardiff** [comment]
@rdp I try to give a shot for [connection pooling in sqlite](https://github.com/crystal-lang/crystal-sqlite3/commit/261f17ad2187269a4f22bad8d76c2b6a2483b3af). And it turns out that all the default settings are the right [ones](https://www.sqlite.org/threadsafe.html). 

Right now the default max_pool_size is 1. Not very useful. Until that is changed you can increase the max_pool_size in the connection uri as follows:

```crystal
require "db"
require "sqlite3"

DB.open "sqlite3:./file2.db?max_pool_size=2" do |db|
  db.exec "create table if not exists contacts (age integer)"
  db.exec "insert into contacts (age) values (33);"
  db.query("SELECT age from contacts") do |rs|
    rs2 = db.query ("select 1;")
  end
end
```

Although sqlite is able to handle this using the same connection, for simplicity it will probably work in crystal via the pool. At least until db incorporates transactions since that might push decisions in some directions.

**Comment by rdp** [comment]
Initially if pool size is 1 I would expected it to at least throw an
exception "immediately" instead of a timeout :)

I guess it uses connection pool capability underneath to "make the default"
more capable but it still surprised me that it was using pools "at all"
when I didn't specify a pool to the open call.
 DB.from_pool
But that's unrelated.
Anyway just thinking aloud :)

On Tue, Oct 18, 2016 at 11:17 PM, Brian J. Cardiff <notifications@github.com

**Comment by asterite** [comment]
@bcardiff I think the default maximum pool size should be unlimited
