### ISSUE TITLE
fails with capitalized column names

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal-db#17]
Not sure if this is expected:

```
require "db"
require "sqlite3"
class Url
  DB.mapping({
    id: Int32,
    url:  {type: String},
  })
end

DB.open "sqlite3:./file.db" do |db|
  db.exec "drop table if exists contacts"
  db.exec "create table if not exists contacts (id integer primary key autoincrement, URL string)"
  db.exec "insert into contacts (url) values (\"url\");"
  rs = db.query("SELECT id, url from contacts")
  Url.from_rs(rs)
end
```

results in 

`
unknown result set attribute: URL (DB::MappingException)`

you can work around it by making URL downcase in the create table statement, or by specifying a key but it feels as if it shouldn't be required [?]
Cheers!

**Comment by asterite** [comment]
The language is not case insensitive, so I don't think this proposal makes much sense... sorry :-)

**Comment by rdp** [comment]
Which language are you referring to as not case insensitive?
Thanks!

**Comment by asterite** [comment]
Nim: https://github.com/nim-lang/Nim/wiki/unofficial-faq#why-is-it-caseunderscore-insensitive

**Comment by bcardiff** [comment]
I do have mixed feelings. On one hand db engines are usually case insensitive when performing queries. Sqlite is preserving the original case of the column here.

```
$ sqlite3 -init file.db
sqlite> .headers on
sqlite> create table if not exists contacts (id integer primary key autoincrement, URL string);
sqlite> insert into contacts (url) values ("url");
sqlite> SELECT id, url as url from contacts;
id|url
1|url
sqlite> SELECT id, url from contacts;
id|URL
1|url
sqlite>
```

`DB::ResultSet` only allows accessing fields in order, no using the name.
In `DB::Mapping` [src](https://github.com/crystal-lang/crystal-db/blob/master/src/db/mapping.cr#L94-L96) we could change the col_name to underscore and also the value used in the `when` clause, but most of the time will be unnecessary operations.

Although we are loosing the case sensitivity in mapping it is better for avoiding extra operations.
At most I would agree on changing the expanded mapping code to allow some column-to-property override that by default will be the identity.

**Comment by rdp** [comment]
Yeah unfortunately in the DB.mapping it doesn't allow all upper case names
as that would work (but it does work if you specify a "key" which is good)

url: {type: String, key: “URL”},

**Comment by rdp** [comment]
Another work around is selecting "as lowercase" like
`
  rs = db.query("SELECT id, url as url from contacts")`

So...I guess since there are "enough" work arounds and "typically" columns are named lowercase by people, fixing this may be a lower prio. Thanks all for the discussion.
