### ISSUE TITLE
Compilation error when running on Crystal 1.6.2

### ISSUE THREAD

**Issue by oatmealine** [crystal-lang/crystal-db#176]
When using this library on the latest version of Crystal (1.6.2), a type error arises:

```
In lib/db/src/db/statement.cr:92:9

 92 | def query(*args)
          ^----
Error: this method overrides DB::StatementMethods#query(*args) which has an explicit return type of DB::ResultSet.

Please add an explicit return type (DB::ResultSet or a subtype of it) to this method as well.
```

Patching this (and a similar error a few lines up) to what the compiler suggests fixes this issue (and no further issues seem to arise), however I was wondering if this was already known / an issue on my side. I'm quite new to Crystal, so I'm unsure if I should even file this issue here.

**Comment by straight-shoota** [comment]
Can describe the steps to reproduce this error?

My guess is that you're maybe using an older version of this shard?

**Comment by oatmealine** [comment]
It appears so - I was relying on a library that locked `crystal-db` to `~> 0.6.0`, and removing that requirement seemed to have fixed it. Thank you!
