### ISSUE TITLE
Error: can't cast to JSON::Any

### ISSUE THREAD

**Issue by ejstembler** [crystal-lang/crystal-db#177]
I'm upgrading from Crystal `1.5.0`, crystal-db `0.10.0`, crystal-pg `0.23.1` and I'm seeing this error:

```
Error: can't cast (Array(PG::BoolArray) | Array(PG::CharArray) | Array(PG::Float32Array) | Array(PG::Float64Array) | Array(PG::Int16Array) | Array(PG::Int32Array) | Array(PG::Int64Array) | Array(PG::NumericArray) | Array(PG::StringArray) | Array(PG::TimeArray) | Array(PG::UUIDArray) | Bool | Char | Float32 | Float64 | Int16 | Int32 | Int64 | JSON::PullParser | PG::Geo::Box | PG::Geo::Circle | PG::Geo::Line | PG::Geo::LineSegment | PG::Geo::Path | PG::Geo::Point | PG::Geo::Polygon | PG::Interval | PG::Numeric | Slice(UInt8) | String | Time | UInt32 | UUID | Nil) to JSON::Any
```

from: 

```crystal
db.scalar(sql).as(JSON::Any)
```

I realize a lot has probably changed, and tips?

**Comment by straight-shoota** [comment]
Hm, yeah you can't actually cast a db result type to `JSON::Any`. There is some overlap with types supported by `JSON::Any` (not as a cast, but as argument to `JSON::Any.new`), but a lot of them can't be represented that way. I'm surprised that this apparently used to work before...?
So I don't think there's a clear answer without knowing the bigger picture of what you're trying to do.

I'm closing this issue. Such a kind of help request is better suited on the [forums](https://forum.crystal-lang.org), feel free to open anew thread over there and make sure to provide some context.

**Comment by bcardiff** [comment]
Hi @ejstembler, I think that what changed is described at https://github.com/will/crystal-pg/pull/232

**Comment by ejstembler** [comment]
@straight-shoota I have a Postgres function which `RETURNS jsonb`. That cast, `db.scalar(sql).as(JSON::Any)`, used to work great before.

@bcardiff Thanks Brian, I'll look into that change in crystal-pg...
