### ISSUE TITLE
feature request: query().each_row

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal-db#18]
Today you have to do:

```
       conn.query("SELECT x from y") do |rs|
         rs.each do
           puts rs.read(String) ...
         end
       end

```

would be nice to have some double loop:

```
       conn.query("SELECT x from y").each_row do |rs|
         puts rs.read(String)
       end
```

**Comment by bcardiff** [comment]
a `QueryMethods#query_each` could be added. 

```
conn.query_each("SELECT x from y") do |rs|
  puts rs.read(String)
end
```

The important thing is to release/close the result_set. Right now is `#query` without block returns a result_set that should be closed by the user, and `#query` with a block ensures the result_set is closed.

**Comment by rdp** [comment]
You rock!
