### ISSUE TITLE
Incorrect documentation example for driver implementers on v0.12.0

### ISSUE THREAD

**Issue by amauryt** [crystal-lang/crystal-db#187]
I am in the process of updating the DuckDB driver for crystal-db v0.12.0, and I think that I found a small documentation error.

In the `Driver` class documentation there is a minimal example to implement a driver by overriding the newly introduced method `connection_builder`,  as can be seen [on this line](https://github.com/crystal-lang/crystal-db/blob/9471b33ffe6620f741a881affc3db41b34febb78/src/db/driver.cr#L10).

However, the example seems to refer to a previous implementation using `Proc(DB::Connection)`, which was discarded in favor of  a `ConnectionBuilder` instance. It seems that the documentation example was not updated after this change.

**Comment by bcardiff** [comment]
Thanks for reporting @amauryt
