### ISSUE TITLE
feature request: RS#map

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal-db#19]
today per row you do

```
    output = [] of String
     rs.each do
       output << rs.read(String)
     end
```

feature request do be able to do it this way:

```
        output = rs.map do
           rs.read(String)
         end
```

or something similar. Thoughts?

**Comment by bcardiff** [comment]
You can use `QueryMethods#query_all` to get an array with all the results [src](https://github.com/crystal-lang/crystal-db/blob/d7fdf1eada852ea084b7b9786e149094ec5270e0/src/db/query_methods.cr#L167)

```
names = db.query_all "select name from contacts", &.read(String)
names = db.query_all "select name from contacts", as: String
contacts = db.query_all "select name, age from contacts", as: {String, Int32}
```

**Comment by rdp** [comment]
OK that's actually pretty close since you can map that to whatever you want...
