### ISSUE TITLE
Having issue with "weak_ref" 

### ISSUE THREAD

**Issue by ColinRioux** [crystal-lang/crystal-db#20]
Not sure if this is simply just something wrong with my setup, however, I've been having trouble building my project because of the `require "weak_ref"` statement in some of the db lib code. 

Here's my log: 
    
    Error in ./src/Chris.cr:8: while requiring "./Chris/*"

    require "./Chris/*"
    ^

    in ./src/Chris/tstorage.cr:2: while requiring "db"

    require "db"
    ^

    in ./libs/db/db.cr:121: while requiring "./db/pool"

    require "./db/pool"
    ^

    in ./libs/db/db/pool.cr:1: while requiring "weak_ref": 
    can't find file 'weak_ref' relative to        
    '/Users/User/_Discord/Chris/libs/db/db'

    require "weak_ref"
    ^

I'm not sure how to "change" the relativity. Any help?

**Comment by asterite** [comment]
What Crystal version are you using? WeekRef was introduced in 0.19.x (I think 0.19.2 or 0.19.3)

**Comment by ColinRioux** [comment]
Oh, I am using 0.19.0, that would probably explain why. I thought I had the latest version, but I think I was mis-upgrading crystal-lang using brew. 

Fixed, thanks!
