### ISSUE TITLE
"Syntax error at end of input (PQ::PQError)" when using `?` in queries

### ISSUE THREAD

**Issue by paulcsmith** [crystal-lang/crystal-db#30]
When using `?` in queries the statement is invalid, but when hardcoding the value or using regular string interpolation, it works fine. Here's an example

```crystal
DB.open("postgres://localhost/my_db") do |db|
  # Result in `syntax error at end of input (PQ::PQError)`
  db.query "select name from contacts where id = ?", 10 
  # Works as expected
  db.query "select name from contacts where id = 10"
  id = 10
  # Works as expected
  db.query "select name from contacts where id = #{id}"
end
```

I'm not sure how to debug this because I couldn't find a method that generates a raw SQL statement to see what is wrong. I also couldn't find a verbose mode that logs what queries are executed.

I do have the code up here so you can take a look and run it yourself. I'll post it in a few minutes

Crystal version:

```
Crystal 0.20.1 (2016-12-05) # On macOS Sierra
```

LLVM:

```
stable 3.9.0 (bottled) # from homebrew
```

Shards:

```yml
version: 1.0
shards:
  db:
    github: crystal-lang/crystal-db
    version: 0.2.2

  pg:
    github: will/crystal-pg
    version: 0.12.0
```

See the code at https://github.com/paulcsmith/migrate.cr/tree/ps-crystal-db-issue-30

Run it yourself by running

```bash
crystal tasks/db/create.cr
crystal tasks/db/migrate.cr
```

The code that is failing is here: https://github.com/paulcsmith/migrate.cr/blob/ps-crystal-db-issue-30/src/migrate/migration.cr#L32
'
Though the code uses `query_one?`, I tried it with `query` and it had the same error

**Comment by bcardiff** [comment]
In PostgreSQL positional arguments are `$1`, `$2`, etc.
`select name from contacts where id = $1`

`?` are used in MySQL and sqlite.

**Comment by paulcsmith** [comment]
@bcardiff That was fast! Thank you! I didn't realize that. For some reason I thought crystal-db would normalize it so queries would work on both mysql and postgres. I'm going to go ahead and make a change to the README so those that run into this know what to expect this for Postgres. Would that be helpful?

**Comment by bcardiff** [comment]
Also, crystal-db does not build raw sql statement. Protocols usually has support for positional arguments which avoids sql injection due to concatenating sql statements.

Sure, some note wouldn't harm. More docs are coming, but go ahead 👍

**Comment by RX14** [comment]
I would very like to see the queries normalised between the two drivers. I think it creates an unnecessary confusion that would be quite easy to fix.

**Comment by bcardiff** [comment]
SQL dialects might differ. `?`/`$1`/`@p1` might seems trivial but then things like `TOP`/`LIMIT` are not that easy. They might appear in subqueries and parsing/changing the statement opens many issues.

An ORM or something like Arel could be built, for sure, but on top of crystal-db would be my opinion.

**Comment by RX14** [comment]
@bcardiff I meant just the interpolation symbols. Translating between SQL dialects is well out of scope.

**Comment by bcardiff** [comment]
Ok, although that is doable it means parsing the sql with escape logic to recognize properly all the positional placeholders.

Each driver can that if wanted. Mysql need to do that to support positional arguments on unprepared queries due to limitation of TextProtocol for example. Or when supporting named argument in the future. There might be some utils to do that, but it will be for sure opt-in of each driver.

**Comment by raydf** [comment]
I'm against normalizing this part, the reasons why, is that some of us use a lot, JetBrains DataGrip , SQL Manager for Postgresql or other tools alike, for complex query designs, and all this tools recognize $1, $2 as parameters.
The reason why postgresql use $1 instead of ? is because some times you can use complex UNIONS statements that use the same parameter more than once.

**Comment by RX14** [comment]
Ok, you've convinced me!

**Comment by rdp** [comment]
JDBC normalizes the queries...maybe it should support both?

**Comment by straight-shoota** [comment]
How does it do that? It either requires each driver to parse SQL queries or have a dedicated syntax for query parameters that is distinct from that of existing SQL dialects.
The former would be much work, and it needs to be implemented in the drivers, not in `crystal-db`. The latter would be easier to accomplish, but I'm not sure if it would be worth creating our own parameter syntax.

**Comment by rdp** [comment]
Yeah my guess is the driver has to parse the queries.  But then at last you can use different DB's with the same query more easily... :)
