### ISSUE TITLE
down again :s

### ISSUE THREAD

**Issue by airinfection** [crystal-lang/crystal-db#33]
20.3 released, it's down again.

**Comment by airinfection** [comment]
(breaking change) The libs directory is no longer in the default CRYSTAL_PATH, use lib (running crystal deps should fix this)

**Comment by airinfection** [comment]
instance variable '@remaining' of MySql::ReadPacket must be Int32, not Nil

Error: instance variable '@remaining' is initialized inside a begin-rescue, so it can potentially be left uninitialized if an exception is raised and rescued

**Comment by Sija** [comment]
Related issue: https://github.com/crystal-lang/crystal-mysql/issues/21

**Comment by bcardiff** [comment]
fixed at 0.3.3
