### ISSUE TITLE
Return column names using typed query?

### ISSUE THREAD

**Issue by samueleaton** [crystal-lang/crystal-db#34]
I noticed that for all of the QueryMethods, there isn't a method that returns the column names with the column values if using the `as: {}` argument.  

If I use `as:` then I have to manually map the  column names, otherwise I have to manually read column types. Is there not a way to get column names while still using `as:`?

If I'm returning 10+ columns, then multiple assignment of the tuple result is too messy.

I'm using crystal-pg.

Thanks! 👍

**Comment by bcardiff** [comment]
If multiple assignment is too noisy you can use #read and split them in multiple lines. You will be iterating manually the resultset. 

Other alternative is to use DB.mapping which should be able reduce noise a little bit since they can be loaded from a resultset.

**Comment by bcardiff** [comment]
But this has nothing to do with column names. Unless i am missing something.

**Comment by samueleaton** [comment]
Thanks for the quick response!! My end goal is to find the quickest way to get the raw result as JSON back to the client. I need the column names for that.

I could probably do the `DB.mapping` and JSON.mapping on a class.

**Comment by RX14** [comment]
Here's an approach I used which decouples the DB structure from the returned JSON structure: https://gist.github.com/RX14/2fddcea68f66325366bdaad7055479c4. I think it's quite a neat way to go from SQL query to returned JSON.

**Comment by bcardiff** [comment]
If you want to stream raw json of the rows check how https://github.com/bcardiff/sample-crystal-db_json is done.

**Comment by samueleaton** [comment]
@RX14 @bcardiff Thanks for the direction
