### ISSUE TITLE
Time data type

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/crystal-db#4]

**Comment by crisward** [comment]
This has been added to the mysql driver - https://github.com/crystal-lang/crystal-mysql/commit/f540d49730c1f93531c7fbc346e3ccbc54d9b57c

**Comment by sdogruyol** [comment]
What's the status on this?

**Comment by crisward** [comment]
It's merged into mysql, not sure about the sqlite support.
https://github.com/crystal-lang/crystal-mysql/blob/master/src/mysql/types.cr#L111

**Comment by crisward** [comment]
https://github.com/crystal-lang/crystal-db/blob/v0.2.0/src/db.cr#L72 is missing type Time. Without this the mysql type time doesn't work.

**Comment by drujensen** [comment]
I added Time and Bool to the base driver.  Here is the PR.  Hopefully this is what is needed to add support.  https://github.com/crystal-lang/crystal-db/pull/24

**Comment by bcardiff** [comment]
@crisward  / @drujensen a db driver can use any type there is no restriction. The list of supported types in crystal-db is to have a minimum set of types known to be shared across drivers. Yet there are no restrictions. Check https://github.com/crystal-lang/crystal-db/blob/master/spec/custom_drivers_types_spec.cr .

Before merging #24, Time support should be added to https://github.com/crystal-lang/crystal-sqlite3 otherwise it will break.

FYI: I will be OOF for a week without a computer to program.

**Comment by drujensen** [comment]
@bcardiff Thanks for referencing the custom types.  I was building my app to the db driver so that I can replace the real driver in the future.

To me, Time and Bool should be apart of a minimum set but understand they are not supported by sqlite.  Should sqlite determine the minimum?

**Comment by drujensen** [comment]
@bcardiff Looking at the shards.yml for the sqlite driver, it properly locks in the version so there shouldn't be an issue merging the PR and add support to the sqlite driver later.  Correct?

**Comment by bcardiff** [comment]
@drujensen as from crystal-mysql v0.2.2 you should be fine to use Time. Despite #24.

It's true that shard.yml fix the version but I want first tackle other stories before adding more types to DB::Any. Any driver should be able to define additional types for extensibility.

**Comment by drujensen** [comment]
@bcardiff Thanks for taking the time to look at this.  I will see if I can work around it.

**Comment by spalladino** [comment]
> Thanks for taking the **time** to look at this
I see what you did there...
