### ISSUE TITLE
Readme example misleading

### ISSUE THREAD

**Issue by stereosteve** [crystal-lang/crystal-db#49]
this line: `db.exec "create table contacts (name string, age integer)"`

should be `db.exec "create table contacts (name TEXT, age INT)"`

Because of sqlite's loose typing, if you change example line: `db.exec "insert into contacts values (?, ?)", "1234", 30`

this line will fail: `puts "#{rs.read(String)} (#{rs.read(Int32)})"`

thusly:

```
cast from Int64 to String failed, at ....../lib/db/src/db/result_set.cr:79 (TypeCastError)
```

Anyway might be confusing to people copy pasting examples

**Comment by luislavena** [comment]
Can you tell us what version of sqlite3 are you using? I was able to run the README example against SQLite 3.14.1 (Ubunut Yakkety 16.10) without issues.

**Comment by hinrik** [comment]
The readme example works fine for me too. However, he's pointing out that if you insert the string `"1234"` into a SQLite `string` field, SQLite stores it as a number and you can't read it back from the database as a `String` (you get an `Int64`). Changing the SQLite datatype to `text` causes it to always be stored as a string.

From the docs (https://sqlite.org/datatype3.html):
> And the declared type of "STRING" has an affinity of NUMERIC, not TEXT.
