### ISSUE TITLE
Error: not supported read

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal-db#54]
This is my DB:

```bash
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type         | Null | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| id        | mediumint(9) | NO   | PRI | NULL    | auto_increment |
| from_addr | varchar(30)  | NO   |     | NULL    |                |
| to_addr   | varchar(30)  | NO   |     | NULL    |                |
| subject   | varchar(30)  | NO   |     | NULL    |                |
| data      | mediumtext   | NO   |     | NULL    |                |
+-----------+--------------+------+-----+---------+----------------+

```

I try to read it using:
```crystal
        @db.query_each "SELECT * FROM mail" do |rs|
          rs.each do
            mail = Servo::Mail.new
            id = rs.read(Int32)
            mail.from = rs.read(String)
            mail.to = rs.read(String)
            mail.subject = rs.read(String)
            mail.data = rs.read(String)
            hash[id] = mail
          end
          rs.close
        end
```

And I get empty or error response

What am I missing

**Comment by elrok123** [comment]
Why are you closing before you finish getting all the results? It seems that you are closing before it finishes. You shouldn't need to close using the block, as the block self terminates. Are you trying to read one result or multiple? I didn't discover ```query_each``` until I'd already written my own version, think the docs on crystal-db and crystal-* need updating as they don't actually cover a lot of the features. Had to dig around to find stuff. Hope this helps.

**Comment by bararchy** [comment]
@elrok123 `rs` needs to be closed manually as per docs.

This is what worked for me in the end + changing mediumint type to integer in the db as it is not supported right now.

```crystal
        @db.query "SELECT * FROM mail" do |rs|
          rs.each do
            mail = Servo::Mail.new
            id = rs.read(Int32)
            mail.from = rs.read(String)
            mail.to = rs.read(String)
            mail.subject = rs.read(String)
            mail.data = rs.read(String)
            hash[id] = mail
          end
          rs.close
        end
```

**Comment by elrok123** [comment]
Where abouts in the docs? I couldn't find anything, I'm curious as I don't have any issues without adding result_set close, so wondering if it'd speed things up

**Comment by girng** [comment]
> Where abouts in the docs? I couldn't find anything, I'm curious as I don't have any issues without adding result_set close, so wondering if it'd speed things up

right here, under the **query** heading ^^
https://crystal-lang.org/docs/database/

`Database#query returns a ResultSet that needs to be closed.`

**Comment by girng** [comment]
oh derp. yeah, thank you
