### ISSUE TITLE
Query hangs indefinitely when null datetime

### ISSUE THREAD

**Issue by cazgp** [crystal-lang/crystal-db#59]
Using with pg, kemal, and crystal version 0.23.

The following works fine when there is data in the `dob` column of the database. However, as soon as there is a `NULL`, the query hangs indefinitely.

```
class User
    DB.mapping({
        id: Int32,
        username: String,
        name: String,
        email: String,
        dob: {type: Time, nilable: true}
    })
end

get_query = <<-SQL
SELECT id, username, name, email, dob
FROM user
SQL

get "/user" do |env|
    env.response.content_type = "application/json"
    DATABASE.query(get_query) do |rs|
        rs.each do
            pp User.from_rs(rs)
        end
    end
    "Something"
end
```

**Comment by beanieboi** [comment]
hey,

this is happening with all Postgres types. the query executes properly if every column has a value. This looks rather critical to me. it makes it impossible to use a database. sadly NULL values are a thing. whats the best way to help out with this?

```
POSTGRES.query("SELECT * FROM entries") do |rs|
      rs.each do
         ....
      end
    end
```

**Comment by beanieboi** [comment]
if I NULL two or more columns, i get an index out of bounds error.

```
Index out of bounds (IndexError)
0x1029fe2c5: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1029fe261: *CallStack#initialize:Array(Pointer(Void)) at ??
0x1029fe238: *CallStack::new:CallStack at ??
0x1029eca75: *raise<IndexError>:NoReturn at ??
0x102a2224a: *Slice(UInt8)@Slice(T)#+<Int32>:Slice(UInt8) at ??
0x102ac034d: *Socket+@IO::Buffered#skip<Int32>:Nil at ??
0x102aba932: *PQ::Connection#skip_bytes<Int32>:Nil at ??
0x102adab85: *PG::ResultSet#skip:Int32 at ??
0x102adc95d: *PG::ResultSet#do_close:Nil at ??
0x102adc88d: *PG::ResultSet@DB::Disposable#close:(Bool | Nil) at ??
0x1029e1f71: __crystal_main at ??
0x1029f65e8: main at ??
```

at least this gives a strack trace?

**Comment by ZeWebDev** [comment]
There is a problem with crystal-pg, when it tries to skip over null values

It doesnt skip values of size 1 when it should be -1

You can fix this by changing

```crystal

#lib/pg/src/pg/result_set.cr

private def skip
    col_size = conn.read_i32
    conn.skip_bytes(col_size) if col_size != 1
    @column_index += 1
  rescue IO::Error
    raise DB::ConnectionLost.new(statement.connection)
  end

#to

private def skip
  col_size = conn.read_i32
    conn.skip_bytes(col_size) if col_size != -1    #change this to -1
    @column_index += 1
  rescue IO::Error
    raise DB::ConnectionLost.new(statement.connection)
  end

```

**Comment by jwoertink** [comment]
I'm also seeing the query hang on this line https://github.com/crystal-lang/crystal-db/blob/master/src/db/mapping.cr#L115 when `{{value[:type]}}` is `Array(String)` using pg. Not sure if it's a pg issue, or db...

**Comment by jwoertink** [comment]
Actually, I think it's `Array(Int16)`, not `Array(String)`. It seems to not even get to my string array in my test.

**Comment by jwoertink** [comment]
Alright, for real this time, turns out it's this https://github.com/will/crystal-pg/issues/105. It just looked like the others because macros are hard to debug lol

**Comment by rdp** [comment]
This is presumed fixed on the linked issues...
