### ISSUE TITLE
Exception:  (DB::PoolTimeout)

### ISSUE THREAD

**Issue by crisward** [crystal-lang/crystal-db#61]
I'm occasionally getting this error with the Mysql driver. 
```
Exception:  (DB::PoolTimeout)
```
These are the pool settings I'm passing in on the end of my url
```
?max_pool_size=50&initial_pool_size=10&max_idle_pool_size=10&retry_attempts=3
```
The database seems to have 5 threads connected, so I'm a but confused as to what's going on, surely it should have 10?

**Comment by crisward** [comment]
I'm closing this, as I have a feeling the logic I was using around my db connection class may have been to blame. I'll perhaps update if the problem re-emerges.

**Comment by girng** [comment]
Seems like `<DB::PoolTimeout:>` exception is called whenever I set `max_pool_size` to 1 or higher.

**Comment by girng** [comment]
I fixed the `<DB::PoolTimeout:>` exception by calling `.close` on a `MySql::ResultSet`.

Example:
```
  # Make sure the db connection is alive, if it's not, we need to kill the app.
  def db_pinger
    loop do
      sleep 1
      result = db.query "/* ping */ SELECT 1"
      pp "checking ping for mysql..."
      puts result
      # result.close
    end
  rescue e
    pp "Lost connection to the MYSQL server, this is fatal."
    exit
  end
```

If you don't have `result.close` there, it will cause the `<DB::PoolTimeout:>` exception.

Weird thing is, I have 50 or so other methods that don't need call `.close`, and I never get this `PoolTimeout` exception. Seems to only happens in loops.

**Comment by bcardiff** [comment]
@girng  use query_one or scalar. That should close the result_set. When result_set is closed connections that were implictly checkout of the pool will return. Maybe that is the difference with respect to other usages of query in your app.

**Comment by girng** [comment]
@bcardiff Aww, you are right. I use all the other query methods instead of `query`. Wow, I derped hard there.
