### ISSUE TITLE
Support for MSSQL

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal-db#66]
Hi, currently, MSSQL is available on Linux and is pretty easy to use via [docker](https://hub.docker.com/r/microsoft/mssql-server-linux/).

I found nothing related to how connect Crystal to Microsoft SQL Server.

Is possible to create an adapter for MSSQL?

**Comment by bcardiff** [comment]
There is no current option for mssql.
A driver would need to either: 

1. implement binding to http://www.freetds.org/ (https://github.com/rails-sqlserver/tiny_tds might serve for inspiration), or 

2. implement the https://msdn.microsoft.com/en-us/library/dd304523.aspx protocol directly to the socket as crystal-pg and crystal-mysql

**Comment by faustinoaq** [comment]
Crystal on Windows is in progress, so, I think a MSSQL binding would be useful, I will try to do something. :smile: (I hope keep my smile)

@fridgerator Did you try to create a MSSQL binding before? how was that?

**Comment by fridgerator** [comment]
@faustinoaq No I never tried to do it in crystal.  I recently had to connect a rails app to a legacy MSSQL server, and used tiny_tds (mentioned above).  It was an unpleasant experience.

**Comment by wonderix** [comment]
Implementing a binding to [freetds](http://www.freetds.org/) will not work, because a calls to the library will block all fibers in crystal. The ruby binding is using `rb_thread_call_without_gvl` to release the global interpreter lock. This will not be possible in crystal.
The only possibility would be to implement the protocol directly. Perhaps [jtds](https://github.com/milesibastos/jTDS) could be a starting point.

**Comment by bcardiff** [comment]
Even though I would encourage a protocol implementation directly, I'm not convinced that freetds can't be wrapped.

It is possible to have a dedicated thread to handle the calls to the library if that is needed by freetds. I did something like that in https://github.com/bcardiff/crystal-fswatch. I am not familiar with freetds though.

**Comment by wonderix** [comment]
I started with an [implementation of tds in plain crystal](https://github.com/wonderix/crystal-tds)
