### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/crystal-db#7]
Should be parametrisable via connection string URI. Ensure it is still possible to quickly setup a new connection without creating a full pool, for quick open-exec-close operations. Must keep track of "busy" and "free" connections.

**Comment by bcardiff** [comment]
started in `feature/pool` branch

**Comment by crisward** [comment]
Any ETA on this being merged? Tried using the for with MYSQL, but got pool exhausted errors.

Thanks.

**Comment by crisward** [comment]
Not sure if this is the place for this, but if like me your connections keep going missing, it's worth knowing you need to manually close result sets if they're not uses inside a block.

ie.
```crystal
get "/users" do |ctx|
  rs = db.query("SELECT id,first_name,surname FROM users")
  users = User.from_rs(rs)
  rs.close # this is important
  users.to_json
end
```
or
```crystal
get "/users" do |ctx|
  db.query("SELECT id,first_name,surname FROM users") do |rs|
    User.from_rs(rs).to_json
  end # gets closed automatically with a block
end
```

**Comment by bcardiff** [comment]
Hi @crisward sorry for the delay.

Things that are pending on the pool branch before merging are:

1. Be able to define connection configuration/setup for a `Database`. So you can be sure things like collation are well set before any other thing is done. 
2. Allow a `Statement` to be re-prepared/executed in other connection if the original connection is busy.

The connection pool will allow you to have multiple connection, but if you are leaking connection you will eventually reach the same problem as you currently do. You will just delay a bit for that.

I would like to invest some time in the following couple of weeks.

You should be able to use `branch: pool` in your shards.yml if you want to try this.

**Comment by crisward** [comment]
Been using crystal db with `branch: pool`,  after a period of time and I get this error. https://gist.github.com/crisward/f2a93c185ed793a1a1dc6da530457efa

I think it may be trying to use a connection perhaps reset by the database (mariadb). Just thought I'd mention incase it's not something you're testing for. I'm only setting up the connection once when I start the app, not creating a connection per request.

**Comment by bcardiff** [comment]
Thanks @crisward for pointing that scenario. I didn't have in mind a connection been close from the server.

**Comment by bcardiff** [comment]
@crisward FYI, I've just updated the pool branch with the features mention in https://github.com/crystal-lang/crystal-db/issues/7#issuecomment-240613743 . 

I still need to come around how to deal with server side connection resets.

**Comment by crisward** [comment]
Cool, I'll update and let you know how I get on.

**Comment by bcardiff** [comment]
@crisward another FYI, it has been a nice day for DB here.
I will wait to gather some more opinions about the api/code before merging, but if you update and use the latest`crystal-mysql/feature/pool`  and `crystal-db/feature/pool` branch you will have a retry/reconnect logic when the connection is lost.

There are some parameters that can be tweaked in the connection uri as url params.

```
  - initial_pool_size (default 1)
  - max_pool_size (default 1)
  - max_idle_pool_size (default 1)
  - checkout_timeout (default 5.0)
  - retry_attempts (default 1)
  - retry_delay (in seconds, default 1.0)
```

The idea is that if you never request a connection explicitly, the statements will be able to reconnect to any available connection and even retry to connect with a fresh connection.

**Comment by crisward** [comment]
Thanks for this, will update and let you know if the disconnects go away.

**Comment by crisward** [comment]
Just left a dev server running for 40 mins, retried and it's still working. Slight pause on first request, but I'm guessing that was the reconnect happening.

Thanks again for this. 

Not sure if your interested, but this has been me reprogramming a small section of node application we have. It's a bit early to do a fair comparison, but at the moment the node version uses 200mb of Ram, and has a response time of 300ms. The crystal version uses about 2mb of Ram and responds in about 3-6ms. So basically 50-100x improvement. The node version has db caching and other things in place which should help the performance at a cost of memory.

**Comment by bcardiff** [comment]
I am interested, it there is anything to fill in https://github.com/crystal-lang/crystal/wiki/Used-in-production feel free to do. Or drop a email in the mailing list for others to know. Thanks for been an early adopter.

**Comment by crisward** [comment]
Not quite in production yet, but seriously considering it over the next 12 months. The eco-system needs a bit of maturing, but it's well on the way. Hopefully I can help to fill some of the gaps as the need arises. Just need to refine my crystal coding.
