### ISSUE TITLE
Proper exception handling.

### ISSUE THREAD

**Issue by HiImJulien** [crystal-lang/crystal-db#75]
Currently I am working on a small project, in order to familiarize myself with Crystal language, Kemal and SQL.

This snippet crashes the whole application, when executed on a empty tables:
```
def self.find(id : Int32)
    id, name, email, password = db.query_one "SELECT * FROM Author WHERE id=?", id, as: {Int32, String, String, String}
   Author.new id, name, email, passowrd
ensure
   nil
end
```
The applications, fortunately, crashes with a complete log:

> no rows (DB::Error)
> 0x10beb2395: *CallStack::unwind:Array(Pointer(Void)) at ??
> 0x10beb2331: *CallStack#initialize:Array(Pointer(Void)) at ??
> 0x10beb2308: *CallStack::new:CallStack at ??
> 0x10beabb35: *raise<DB::Error>:NoReturn at ??
> 0x10bfc13fb: *DB::Database@DB::QueryMethods#query_one:as<String, Int32, Tuple(Int32:Class, String:Class, String:Class, String:Class)>:Tuple(Int32, String, String, String) at ??
> 0x10bfbf3c7: *Author::find<Int32>:Author at ??
> 0x10beac837: ~procProc(HTTP::Server::Context, Author)@src/api/author.cr:15 at ??
> 0x10beacf3b: ~proc4Proc(HTTP::Server::Context, String)@lib/kemal/src/kemal/route.cr:10 at ??
> 0x10bfbb055: *Kemal::RouteHandler#process_request<HTTP::Server::Context>:String at ??
> 0x10bfbaf29: *Kemal::RouteHandler#call<HTTP::Server::Context>:String at ??
> 0x10bfb5658: *Kemal::FilterHandler@HTTP::Handler#call_next<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfb5091: *Kemal::FilterHandler#call<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfe639a: *Kemal::StaticFileHandler@HTTP::Handler#call_next<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfe5eaf: *Kemal::StaticFileHandler#call<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfe50ef: *Kemal::CommonExceptionHandler@HTTP::Handler#call_next<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfe4c60: *Kemal::CommonExceptionHandler#call<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfe4246: *Kemal::CommonLogHandler@HTTP::Handler#call_next<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfe13f1: *Kemal::CommonLogHandler#call<HTTP::Server::Context>:HTTP::Server::Context at ??
> 0x10bfba27e: *Kemal::InitHandler@HTTP::Handler#call_next<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfb9eca: *Kemal::InitHandler#call<HTTP::Server::Context>:(Bool | File::PReader | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | OpenSSL::SSL::Socket+ | String | Nil) at ??
> 0x10bfecb19: *HTTP::Server::RequestProcessor#process<(OpenSSL::SSL::Socket::Server | TCPSocket+), (OpenSSL::SSL::Socket::Server | TCPSocket+), IO::FileDescriptor>:Nil at ??
> 0x10bfec515: *HTTP::Server::RequestProcessor#process<(OpenSSL::SSL::Socket::Server | TCPSocket+), (OpenSSL::SSL::Socket::Server | TCPSocket+)>:Nil at ??
> 0x10bfe7a16: *HTTP::Server#handle_client<(TCPSocket+ | Nil)>:Nil at ??
> 0x10beaf8a6: ~procProc(Nil)@/usr/local/Cellar/crystal-lang/0.23.1_3/src/http/server.cr:163 at ??
> 0x10beca834: *Fiber#run:(IO::FileDescriptor | Nil) at ??
> 0x10bea77a9: ~proc2Proc(Fiber, (IO::FileDescriptor | Nil))@/usr/local/Cellar/crystal-lang/0.23.1_3/src/fiber.cr:29 at ??

As far as I understand, they __ensure__ in the function should actually catch this error. Also at this point I am not sure, whether this is Crystal, DB or SQLite3 bug or even intented behaviour.

**Comment by bcardiff** [comment]
Hi @HiImJulien, It is the intended behaviour. Probably you are looking for `query_one?` method. The one with a trailing `?` works for the scenarios were no results might be found, hence the return type will be a nilable value.

Feel free to check the rest of the QueryMethods methods: http://crystal-lang.github.io/crystal-db/api/0.4.3/DB/QueryMethods.html#query_one%3F%28query%2C%2Aargs%2Castypes%3ATuple%29-instance-method

**Comment by RX14** [comment]
You also seem to misunderstand ensure. Rescue is used for catching exceptions, ensure doesn't catch exceptions it just ensures certain clean up code runs whether there's an exception or not. The exception is re-raised once ensure it complete.

**Comment by HiImJulien** [comment]
@RX14 Thanks for clarifying this since I totally misinterpreted the documentation.

I updated my queries as following:
 ```crystal
     def self.find(email : String)
          row = db.query_one? "SELECT * FROM Author WHERE email=?", email, as: {Int32, String, String, String}
          row ? Author.new *row : nil
      end 
```

Thanks for the quick help, cheers!
