### ISSUE TITLE
Query_one? method delegates incorrectly to query_one

### ISSUE THREAD

**Issue by robdavid** [crystal-lang/crystal-db#85]
https://github.com/crystal-lang/crystal-db/blob/be139c900c86e28b150b9808c74d2a4dd2bb913b/src/db/query_methods.cr#L172

The above linked line calls query_one, rather than query_one?, and so throws an error rather than returns nil in the case of no rows found.

**Comment by RX14** [comment]
Yep, it does. Please could you send a PR for this one-character fix?

**Comment by robdavid** [comment]
One character fix PR created, plus unit test :-)

**Comment by bcardiff** [comment]
Fixed by c54fab415e197d1699882454989df890594a6486 in #86
