### ISSUE TITLE
[docs] improve search results for keywords in docs

### ISSUE THREAD

**Issue by ghost** [crystal-lang/crystal-db#90]
https://github.com/crystal-lang/crystal-db/blob/be139c900c86e28b150b9808c74d2a4dd2bb913b/src/db/mapping.cr#L1

look here, at all that great mapping information.

however, when u search the the docs:
![](https://i.gyazo.com/8977aecbad85092a891977a73e11ca64.png)

can't find any information about the DB.mapping stuff

imo, would help a lot

**Comment by z64** [comment]
It's not on `DB::Mappable`, the mapping macro is `DB.mapping` - on `DB`.

http://crystal-lang.github.io/crystal-db/api/0.5.0/DB.html#mapping%28properties%2Cstrict%3Dtrue%29-macro

**Comment by girng** [comment]
> It's not on DB::Mappable, the mapping macro is DB.mapping - on DB.

yeah, but when a user searches map, imo it should show a result that links to that

**Comment by z64** [comment]
i believe the issue is the docs page was generated with the older docs gen that does not include method/macro search

**Comment by bcardiff** [comment]
0.5.1 has been published and the docs were generated with an up to date version of the tool.

![screen shot 2018-11-07 at 16 05 58](https://user-images.githubusercontent.com/459923/48154315-0f5d7900-e2a7-11e8-9d4e-429a9eecc8b7.png)
