### ISSUE TITLE
can't use = ? with db.query_all

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal-db#91]
error:
```
in src/LoginHandler.cr:203: no overload matches 'DB::Database#query_all' with types String, Int64, Int32
Overloads are:
 - DB::QueryMethods#query_all(query, *args, &block)
 - DB::QueryMethods#query_all(query, *args, as types : Tuple)
 - DB::QueryMethods#query_all(query, *args, as types : NamedTuple)
 - DB::QueryMethods#query_all(query, *args, as type : Class)

    items = DB_User_Items.from_rs(db.query_all("select itemid, rpg_items_id, slot_position, q from rpg_user_items where rpg_character_id = ? and user_id = ? and in_stash = 0", client.selected_characterid, client.user_id))
                                     ^~~~~~~~~
```

from

```
    items = DB_User_Items.from_rs(db.query_all("select itemid, rpg_items_id, slot_position, q from rpg_user_items where rpg_character_id = ? and user_id = ? and in_stash = 0", client.selected_characterid, client.user_id))
```

however,
```
    items = DB_User_Items.from_rs(db.query("select itemid, rpg_items_id, slot_position, q from rpg_user_items where rpg_character_id = ? and user_id = ? and in_stash = 0", client.selected_characterid, client.user_id))
```

works just fine

is it possible to add `= ?` support for query_all too? not sure if i am doing it right however, but yeah

**Comment by z64** [comment]
The query is just an opaque string to the library, it doesn't care what the query string is

The issue is that you're missing the `type` argument, which is a forced named argument `as` since it comes after the splat

```cr
items = db.query_all("query", client.selected_characterid, client.user_id, as: DB_User_Items)
items # Array(DB_User_Items)
```

Example in documentation:
http://crystal-lang.github.io/crystal-db/api/0.5.0/DB/QueryMethods.html#query_all%28query%2C%2Aargs%2Castype%3AClass%29-instance-method

**Comment by girng** [comment]
you don't need the as: DB_User_Items if you use from_rs

**Comment by z64** [comment]
`db.query_all` does not return a result set. It returns an `Array(T)`, where `T` is whatever you specify with `as`. This is why you get a "no overload matches" - this method does not work like `db.query`.

**Comment by girng** [comment]
i'm sorry but i don't understand. so if i need to use query_all w/ from_rs, I need to use `, as: DB_User_Items` and `from_rs`? 

the entire point of using from_rs (from what i understand) is to make it simple so you don't need to use , as: DB_User_Items though

**Comment by z64** [comment]
The difference is that these methods work entirely differently:

1. `db.query` *returns* `ResultSet`. If you want your custom mapped type to be used, you use `MyType.from_rs(result_set)

2. `db.query_all` *does not* return a `ResultSet`. It *already returns* the objects of the type you requested. `db.query_all("foo", as: MyMappedType)` *returns* `Array(MyMappedType)`.

What is the issue with specifying `as`?

**Comment by girng** [comment]
yeah, good point tbh.

 i still sense something fishy is going on here, but i accept it and ty for the explanations and help. it's clearer now

**Comment by z64** [comment]
No problem :) I recommend just trying it in your code in a simple example outside of a complex project  and comparing the two to make sense of the differences. 

You can see the source for query_all too, and follow what methods it calls in order to deliver you the final Array.
