### ISSUE TITLE
default key for db.mapping not working

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal-db#92]
check this out

### class DB_User_Items: 
```
macro everything_mapping(a)
 JSON.mapping({{a}})
  DB.mapping({{a}})
end

class DB_User_Items
  everything_mapping({
    itemid:           Int64,
    slot_position:    {type: String, default: "0,0"},
  })
end
```

### query:
```
    items = db.query_all "select itemid, slot_position from rpg_user_items where rpg_character_id = ? and user_id = ? and in_stash = 0", client.selected_characterid, client.user_id, as: DB_User_Items
```

### code
```
    items.each do |item|
      puts item.slot_position
    end
```

`puts item.slot_position` is blank. but i set its default to **`0,0`**

### Database Value:
![image](https://user-images.githubusercontent.com/36117592/45270816-3984ed00-b456-11e8-9a9c-030997f52b17.png)

edit1: i also tried doing `DB_User_Items.from_rs`, but still the same
edit2: i don't know crystal internals that well, but the possible culprit could be around here:
https://github.com/crystal-lang/crystal-db/blob/master/src/db/mapping.cr#L127

**Comment by z64** [comment]
I think the only sane thing to do here is to return exactly what the database has stored. An empty string might be significant in any applications business logic, to do otherwise might be surprising.

You can of course write your own converter if you want an empty string to be treated like this in your own app. Something similar to this should work using a reusable converter class:
```cr
module EmptyStringDefault
  def self.from_rs(rs)
    string = rs.read(String)
    return "Unknown" if string.empty?
    string
  end
end

struct User
  DB.mapping(
    name: String,
    address: {type: String, converter: EmptyStringDefault}
  )
end
```

**Comment by girng** [comment]
@z64 interesting. never seen the converter thing before. thanks for sharing it.

i mean a default value of an empty string should use the default value set. if not, why is it called default then?

**Comment by z64** [comment]
>  if not, why is it called default then?

The conditions around when `default` is used is explicitly for when the database reports `NULL`, or the column was not present in the RS. As documented:

> default: value to use if the property is missing in the result set, or if it's null and nilable was not set to true.

**Comment by girng** [comment]
> or if it's **null** and nilable was not set to true.

what's an empty string though? that's not fair towards strings because they can be empty

**Comment by z64** [comment]
There is no reason for this opinionated & breaking change. `default` is documented and clear about how it works. If you want something different, writing a converter only takes a moment.

**Comment by z64** [comment]
> it's not opinionated at all. i want to store a default value for an empty string...

Yes. *You* want this behavior. That fits *your* application. It may not fit *other* people's applications that already rely on empty strings being left alone, and not subject to `default`. This is what I mean by "opinionated". 

The workaround converter is only a few lines of code that I provided for you in my first comment.

> and the docs tell us how to do it and it's not working

The docs don't say anything about empty strings. It's clear and explicit that the `default` keyword only handles `NULL` / column presence, and nothing else.

> if you want to say this is a "breaking change" nice personal attack against me. 

I'm sorry, I don't understand where this is coming from. It's not an "attack" on anyone.. It's *factually* a breaking change.

The current behavior is that empty strings are not handled by the `default` keyword. If you change this behavior, *that is a breaking change*. People will *have* to change their code if they do not want this updated behavior, or if they already rely on empty strings being left alone, their applications will stop functioning correctly.

These are important things to consider when changing code that so many people (every single major database shard) relies upon.

**Comment by girng** [comment]
> Yes. You want this behavior. That fits your application. It may not fit other people's applications that already rely on empty strings being left alone, and not subject to default. This is what I mean by "opinionated".

no. but nice try to put words in my mouth.

you must think i'm creating this entire issue to make breaking changes that ruin the db module for everyone else! that's certainly not true at all. i made the issue because in the docs it SPECIFICALLY tells you, you can set a default value for a nil (what's an empty string?), value. and i did, and it's not working. it's that simple man.

> These are important things to consider when changing code that so many people (every single major database shard) relies upon.

these are important changes to consider, for the dev team. not some random game dev.

**Comment by girng** [comment]
> The docs don't say anything about empty strings. It's clear and explicit that the default keyword only handles NULL / column presence, and nothing else.

that's not true. it specifically says "value"

> default: value to use if the property is missing in the result set, or if it's null and nilable was not set to true.

**Comment by ysbaddaden** [comment]
Crystal has strong types and `""` *is* a value —in fact Ruby does the same. This isn't JavaScript where an empty value is falsy (such as `[]` or `""`).

`DB` is a **low-level** database abstraction API. `DB.mapping` is a **low-level** convenience, it's **not a high level** ORM that may consider that an *empty* or *blank* value is a missing value and thus should be replaced by the default.

You can switch to a higher level ORM (there are many) or you can stick to DB, and you must take care of low level details, such as specifying custom converters to use the default value when the value is nil, empty, blank, ...

**Comment by girng** [comment]
yes, i am trying to take care of low level details, that's why i want to use `default` lol.
and this module has been good to me i'm not trying to ruin it for everyone, and apologize if it came off that why. i think my problem stems from ysbaddaden' s first two sentences. my previous knowledge is just not consistent with crystal. will close sorry for all this trouble, i'lll use the converter.

**Comment by girng** [comment]
however, for this record.. this experience will not stop me from making any more issues. if i feel something is not right i will speak up about it, i don't want to think i'm that stupid, ok. if explained, i will listen and appreciate the insight
