### ISSUE TITLE
Minor version increase

### ISSUE THREAD

**Issue by nthapaliya** [crystal-lang/crystal-db#93]
I've been running into problems caused by this bug: https://github.com/crystal-lang/crystal-db/issues/85

The PR to fix it has been merged: https://github.com/crystal-lang/crystal-db/pull/86

I ask that you bump the version number, and update the shard for `crystal-sqlite3` to include this fix.

**Comment by rishavs** [comment]
same here. I am forced to create an error wrapper just to handle this bug. Would love a release on this.

**Comment by bcardiff** [comment]
0.5.1 has been released with that fix. Apologies for the delay.
