### ISSUE TITLE
query_all with &.read magically converts "array of values" into Tuple

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal-db#97]
https://github.com/crystal-lang/crystal-db/blob/master/src/db/query_methods.cr#L198

 the description says:

    # Executes a *query* and yield a `ResultSet` positioned at the beginning
    # of each row, returning an array of the values of the blocks.
    #
    # ```
    # names = db.query_all "select name from contacts", &.read(String)
    # ```

#### Example Code:
```
results = db.query_all "select id, username from users", &.read(Int32, String)
puts results
puts typeof(results)
```
#### Output:

```
[{31, "TestUser92"}]
Array(Tuple(Int32, String))
```

the description says an *array of the values of the blocks*. but, it's an array of a Tuple.. an **array of the values** would indicate (to me anyway) of a result of:
```
[[31, "TestUser92"]]
```

or maybe i'm missing something, if so i apologize.. just the wording here could be more explicit maybe?

**Comment by girng** [comment]
tested with just one type:
```
          results = db.query_all "select username from users", &.read(String)
          puts results
          puts typeof(results)
```

#### Output:
```
["TestUser92"]
Array(String)
```

which is correct, but when you supply more than 1 type it becomes a tuple of values, not an array of values

**Comment by girng** [comment]
I guess "of the blocks" is inferring it will be a Tuple. But my example above would have outputted:
{"TestUser92"}

**Comment by rdp** [comment]
Appears the docs for read(multiple types) is that it's a Tuple.  http://crystal-lang.github.io/crystal-db/api/0.11.0/DB/ResultSet.html#read%28%2Atypes%3AClass%29-instance-method My guess is because that way the read method can return "multiple values" but still be type safe and specific...so it's like a type specific array.  I guess that's OK? :)

**Comment by straight-shoota** [comment]
`read(Foo)` reads a single type, `read(Foo, Bar)` reads a tuple of types. So the output value of the block is a tuple. This is all fine.
